### PR TITLE
Upgrade solidity and truffle in preparation for KIP-1

### PR DESCRIPTION
**Pull request by hiddentao**
* Upgrade to solidity 0.5.4
* Upgrade Truffle to 5.0.5
* Switch from Solium to Solhint as former doesn't support Solidity 0.5+
* Switch to custom version of solidity-coverage that supports Solidity 0.5+

Precursor to #22

### CODE REVIEW

**Comment by hiddentao** [comment]
@makoto Please review

**Comment by makoto** [comment]
With this new contract, does the `app` and `server` work as is? For some reason, I start getting "out of gas" when trying to RSVP.

**Comment by hiddentao** [comment]
Just did a full test, all works.

In order to test this locally you have to ensure `app` and `server` use the local version of the contracts repo rather than the NPM package. This involves using `yarn link`. My guess you probably didn't do this, hence the app was trying to use the current published ABI against the contract locally deployed with slightly different bytecode

**Review by makoto — APPROVED** [review]

**Comment by makoto** [comment]
Did `yarn link` and working. FYI, I noticed a few things below but not sure if it was like this from before or not.

1. When RSVP, I can do it from metamask, but failing to do so from browser in incognite mode (which by default should try to connect as accounts[0].
2. When creating an event or RSVP, it waits for confirmation event but it does not seem responding so I had to refresh the page.

**Comment by hiddentao** [comment]
@makoto Thanks.

Regarding the points you've raised:

1. Not sure about this, I don't usually test incognito mode, I'll take your word for it. Would be interested in knowing more about your setup.

2. This is a general problem with our site, will be addressed in https://trello.com/c/qWQ4dOwM/261-backend-save-pending-actions-in-case-user-refreshes-pages-and-thus-increase-minimum-backend-confirmations-to-4-1-for-dev-and-loc

**Pull request merged**
